image: python:3.7.4-alpine3.10

pipelines:
  branches:
    master:
      - step:
          services:
            - docker
          caches:
            - pip
          script:
            - pip3 install awscli
            - IMAGE="public.ecr.aws/r4y0e1p4/spotify-listening-party-frontend"
            - IMAGE_2="public.ecr.aws/r4y0e1p4/spotify-listening-party-api"
            - TAG=${BITBUCKET_BRANCH:-$BITBUCKET_TAG}
            - aws configure set aws_access_key_id "${AWS_KEY}"
            - aws configure set aws_secret_access_key "${AWS_SECRET}"
            - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/r4y0e1p4
            - docker build -t $IMAGE:$TAG ./frontend/
            - docker push $IMAGE:$TAG
            - docker build -t $IMAGE_2:$TAG ./api/
            - docker push $IMAGE_2:$TAG
