version: "3.5"

services:
  frontend:
    build:
      context: ./frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/home/node
      - /home/node/node_modules
    links:
      - api
    networks:
      - app-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ./api:/home/node
      - /home/node/node_modules
    networks:
      - app-network

networks:
  app-network:
    name: app-network
