export const container: string
export const playlistContainer: string
export const tracklistContainer: string
export const queueContainer: string
export const chatContainer: string
export const toggleChat: string
export const visible: string
export const title: string
export const clearQueue: string
