export const container: string
export const roomName: string
export const roomActions: string
export const rooms: string
export const availableRoomsContainer: string
export const room: string
export const info: string
export const public: string
export const listeners: string
